language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
  - bower_components
branches:
  only:
    - master
addons:
  firefox: 46
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polymer-cli
- bower prune
- bower install
script:
- xvfb-run polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
