language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
  - bower_components
branches:
  only:
    - master
addons:
  firefox: '46.0'
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower prune
- bower install
- polylint
script:
- wct -s 'default'
