language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
  - bower_components
branches:
  only:
    - master
addons:
  sauce_connect: true
before_script:
- npm install -g bower polylint web-component-tester
- bower prune
- bower install
- polylint
script:
- wct -s 'default'
